# Generated by Django 4.1.7 on 2023-03-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ecologiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='цена')),
                ('foto', models.ImageField(upload_to='eco_foto/', verbose_name='фото')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'экологичесике товары для посудомойки',
                'verbose_name_plural': 'экологичесике товары для посудомойки но другие',
                'ordering': ['price'],
            },
        ),
    ]
