# Generated by Django 4.1.7 on 2023-03-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_eco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('photo_forms', models.ImageField(upload_to='support/')),
            ],
        ),
        migrations.AlterField(
            model_name='ecologiya',
            name='slug',
            field=models.SlugField(max_length=16, unique=True, verbose_name='слаг'),
        ),
    ]
