# Generated by Django 4.1.7 on 2023-04-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_eco', '0002_support_alter_ecologiya_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecologiya',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='support',
            name='photo_forms',
            field=models.ImageField(upload_to='support/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='support',
            name='text',
            field=models.TextField(blank=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='support',
            name='title',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
    ]
